version: "3"

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: 'student'
      POSTGRES_USER: 'nitiwat'
      POSTGRES_PASSWORD: "springdemo"
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: {}